apiVersion: apps/v1
kind: Deployment
metadata:
  name: resnet-deployment-piserver
spec:
  selector:
    matchLabels:
      app: resnet-server
  replicas: 1
  template:
    metadata:
      labels:
        app: resnet-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: piserver
      containers:
      - name: resnet-container-piserver
        image: syang1690/resnet-serving:latest-arm64
        ports:
        - containerPort: 8500
          name: grpc-port
        - containerPort: 8501
          name: rest-port
