apiVersion: v1
kind: Service
metadata:
  labels:
    run: detection-service
  name: detection-service
spec:
  ports:
  - port: 8500
    targetPort: 8500
    name: grpc
  - port: 8501
    targetPort: 8501
    name: rest
  selector:
    app: detection-server
  type: LoadBalancer
